version: "3.8"

services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3000
    command: yarn start
    env_file: .env.development.local


  # API Prod
  # The example below is of a prod instance. Ideally prod shouldn't be `build`ing anything, it should be done via CI (like github actions!)
  app_prod:
    image: ghcr.io/jaycammarano/encryptjs-frontend:latest
    ports:
      - 3002:3002